### ISSUE TITLE
De-facto but not official ARINC 653 standard capabilities

### ISSUE THREAD

**Issue by stevevestal** [saeaadl/arinc653#1]
On talking to people about their experience with existing RTOS products, there seem to be some de-facto common practices that are not part of the (old) ARINC 653 standard.  Should the AADL ARINC 653 Annex subcommittee consider adding things to the Annex that are not found in the ARINC standard but most/all vendors provide in a common way? 

Here are two examples based on four RTOS products we were able to ask people about.

There is some notion of overall module mode of operation, and different partition schedules may be specified for different module modes.  (I don't know about the exact timing and semantics for transitioning between partition schedules.)

There are a set of options for the API provided in a partition beyond just APEX (POSIX being a particularly common other choice).  This can be specified differently for different partitions.

The proper way to do this is talk the ARINC committee into doing it.  The newly issued ARINC 653 should be checked.  But an Annex provides guidelines, the subcommittee could decide to do such a thing as a useful guideline so AADL tool developers don't specify their own differing tool-specific property sets for something that really is common across RTOSes.

**Comment by khoroshilov** [comment]
> There is some notion of overall module mode of operation, and different partition schedules may be specified for different module modes. (I don't know about the exact timing and semantics for transitioning between partition schedules.)

I guess it is about Multiple Module Schedules described in ARINC-653 part 2?

**Comment by jjhugues** [comment]
Closing, as we do not want to standardize implementation-specific configurations parameters.
